### ISSUE TITLE
Nauta compilation failure:  Error 2

### ISSUE THREAD

**Issue by fjmatos** [IntelAI/nauta#4] opened 2019-02-15 15:25 UTC
I´m trying to install Nauta in a ubuntu 16.04 LTS.

When I run :  make k8s-installer-build

I get this kind of error: 
TASK [container-build : set_fact] **************************************************************************
Friday 15 February 2019  13:41:32 +0000 (0:00:03.190)       0:01:36.086 *******
ok: [local]

TASK [container-build : Wait for tasks] ********************************************************************
Friday 15 February 2019  13:41:33 +0000 (0:00:00.766)       0:01:36.853 *******
included: /nauta/tools/container-build/tasks/wait.yml for local
included: /nauta/tools/container-build/tasks/wait.yml for local
included: /nauta/tools/container-build/tasks/wait.yml for local
included: /nauta/tools/container-build/tasks/wait.yml for local
included: /nauta/tools/container-build/tasks/wait.yml for local

TASK [container-build : Wait for task shared/build/metrics] ************************************************
Friday 15 February 2019  13:41:34 +0000 (0:00:01.023)       0:01:37.876 *******
FAILED - RETRYING: Wait for task shared/build/metrics (3600 retries left).
FAILED - RETRYING: Wait for task shared/build/metrics (3599 retries left).
FAILED - RETRYING: Wait for task shared/build/metrics (3598 retries left).
FAILED - RETRYING: Wait for task shared/build/metrics (3597 retries left).
FAILED - RETRYING: Wait for task shared/build/metrics (3596 retries left).
FAILED - RETRYING: Wait for task shared/build/metrics (3595 retries left).
FAILED - RETRYING: Wait for task shared/build/met

After some retries, the scripts shows:

TASK [container-build : Wait for task shared/run/tensorflow/py3.6] *****************************************
Friday 15 February 2019  14:33:16 +0000 (0:04:29.250)       0:53:19.465 *******
fatal: [local]: FAILED! => {"ansible_job_id": "321866871359.23364", "attempts": 1, "changed": false, "finished": 1, "msg": "Error pulling image 127.0.0.1:32768/nauta/shared/run/tensorflow/py3.6:d8526b2b739b33e5bf1d27fb64a29a4efe0a450d - 404 Client Error: Not Found (\"manifest for 127.0.0.1:32768/nauta/shared/run/tensorflow/py3.6:d8526b2b739b33e5bf1d27fb64a29a4efe0a450d not found\")"}

And finally  stops with Error 2 : 

Makefile:9: recipe for target 'build' failed
make[3]: *** [build] Error 2
make[3]: Leaving directory '/nauta/tools/container-build'
Makefile:210: recipe for target '/nauta/tools/.workspace/tools/1.0.0-20190215133832/tools/shared.tar.gz' failed
make[2]: *** [/nauta/tools/.workspace/tools/1.0.0-20190215133832/tools/shared.tar.gz] Error 2
make[2]: Leaving directory '/nauta/tools'
Makefile:60: recipe for target 'tools-release' failed
make[1]: *** [tools-release] Error 2
make[1]: Leaving directory '/nauta'
Makefile:52: recipe for target 'k8s-installer-build' failed
make: *** [k8s-installer-build] Error 2

¿Can someone help me to avoid this error to finish the installation?
Thanks in advance.

**Comment by mgumowsk** [comment] 2019-02-18 11:22
Hi Javier, 
thanks for letting us know about the issue. Can you please tell me if you tried to build the tagged branch https://github.com/IntelAI/nauta/tree/v1.0.0-beta.0 or just develop branch https://github.com/IntelAI/nauta/tree/develop ?
Also if possible can you post full output from the build - I believe there was an error during building tensorflow at some point earlier.

**Comment by fjmatos** [comment] 2019-02-18 14:43
Hello mgumowsk:

I have cloned using :  #git clone --recursive https://github.com/IntelAI/nauta.git
and then I have run:   #cd /nauta &&  make k8s-installer-build

[make-k8s-installer-build.log.txt](https://github.com/IntelAI/nauta/files/2876105/make-k8s-installer-build.log.txt)

**Comment by mgumowsk** [comment] 2019-02-18 15:51
Hi Javier,
in the provided log I can see an error about lack of free space:
`Monday 18 February 2019  12:24:34 +0000 (0:00:00.349)       0:04:58.521 *******
fatal: [local]: FAILED! => {"ansible_job_id": "773893671130.9994", "attempts": 320, "changed": false, "finished": 1, "msg": "Error building 127.0.0.1:32768/nauta/rpm/kubernetes - code: None, message: Error processing tar file(exit status 1): write /root/rpmbuild/kubernetes/server/kubernetes-server-linux-amd64.tar.gz: no space left on device`

Please verify that you have enough free disk space on the device, 20GB or more - the process of building docker images is very disk consuming.

**Comment by fjmatos** [comment] 2019-02-18 18:32
Thank you, mgumowsk.
I have added additional 50 GB disk , where I have created a directory called nauta, and moved all files.
Now I don´t see space problem in the log but I still get the same error.
[make-k8s-installer-build.log.txt](https://github.com/IntelAI/nauta/files/2876993/make-k8s-installer-build.log.txt)

**Comment by mgumowsk** [comment] 2019-02-19 15:35
Hi Javier,
this time the error is different, we're investigating the issue and we'll let you know shortly about the solution.

**Comment by ajoskowski** [comment] 2019-02-20 15:07
Hi @fjmatos,
Probably something wrong with docker registry data was happened.
Please run `make k8s-installer-clean` which cleans temporary data and later try to build once again using `make k8s-installer-build` command.

**Comment by fjmatos** [comment] 2019-02-20 17:33
Hi @ajoskowski 
I have run , make k8s-installer-clean ,  and then  `make k8s-installer-build` ,  but I get the same error.

ncluded: /nauta/tools/container-build/tasks/wait.yml for local

TASK [container-build : Wait for task shared/centos/rpm-packer] ***************************************
Wednesday 20 February 2019  17:22:51 +0000 (0:00:00.565)       0:20:24.637 ****
fatal: [local]: FAILED! => {"ansible_job_id": "138845617195.16433", "attempts": 1, "changed": false, "fmsg": "Error building 127.0.0.1:32772/nauta/shared/centos/rpm-packer - code: None, message: manifest fo772/nauta/shared/centos:1fe8ee8dfbb8871c149ec50114009b355ed639cd not found, logs: ['Step 1/11 : ARG BAS:7.4.1708', '\\n', 'Step 2/11 : FROM ${BASE_IMAGE}', '\\n']"}


I don´t understand why in the error  los I see  ".../nauta/shared/centos:..."   ,  when my os is  Ubuntu.

**Comment by ajoskowski** [comment] 2019-02-21 06:36
Javier,
You see centos, because this is a building process of docker images which are necessary for platform deployment. Currently we cannot reproduce your problem, but we are testing various scenarios of build run. When we find a reason of your problem, we will send you a tip.

One more question, did you follow the steps which are described [here](https://github.com/IntelAI/nauta/blob/develop/docs/installation-and-configuration/How_to_Build_Nauta/HBN.md)? Do you have at least 12 GB of RAM?

**Comment by fjmatos** [comment] 2019-02-22 07:44
@ajoskowski 
I have followed the guidelines in the documentation.
My kubernetes master node got 12 GB Ram, 2 GB in the worker nodes.
50 GB HD in the master, 10 GB HD in the worker nodes.
I´m running make in the master.
All nodes connect fine because I can deploy containers.
I have checked installation and I got all the docker packages.
So I think I meet all the requirements.

**Comment by ajoskowski** [comment] 2019-02-27 09:21
Hi @fjmatos,
Last time we implemented some changes in installer build process. Now it should be more stable and quicker. Please pull new changes from develop branch and try to run `make k8s-installer-clean` and later `make k8s-installer-build` commands. If you encounter on any problem, please give us a feedback with logs.

**Comment by fjmatos** [comment] 2019-02-27 11:48
Hi @ajoskowski 
I´m not sure if I´m using development branch, but this are the steps I have taken.

#git clone --recursive https://github.com/IntelAI/nauta.git
Cloning into 'nauta'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 20630 (delta 5), reused 9 (delta 4), pack-reused 20617
Receiving objects: 100% (20630/20630), 31.20 MiB | 10.81 MiB/s, done.
Resolving deltas: 100% (11005/11005), done.
#make k8s-installer-clean
08813b84506e
#make k8s-installer-build

but I get the same error.

[make-k8s-installer-build.log.txt](https://github.com/IntelAI/nauta/files/2910096/make-k8s-installer-build.log.txt)

**Comment by ajoskowski** [comment] 2019-02-27 12:12
@fjmatos , you are using old version of code, I see that in logs you have included:
```
TASK [cache-registry-init : Start cache registry container] ***********************************************
Wednesday 27 February 2019  11:12:29 +0000 (0:00:00.048)       0:00:03.006 ****
changed: [local]
```
which is a part of removed code.

Please show me `git log` command output. Hash of your top commit should be 57dcdc7ae2b1c79a07dbb4af9d4d36d89a4d4f2d.

If you've other hash, please run the following commands:
```
git checkout develop
git pull
git reset --hard origin/develop
```

**Comment by fjmatos** [comment] 2019-02-27 12:36
This is the output of the checkout:

#git checkout develop
Already on 'develop'
Your branch is up-to-date with 'origin/develop'.

[git-log.txt](https://github.com/IntelAI/nauta/files/2910284/git-log.txt)

**Comment by ajoskowski** [comment] 2019-02-27 12:41
@fjmatos , you are not up-to-date with origin/develop.
Please run `git pull && git reset --hard origin/develop`.

**Comment by fjmatos** [comment] 2019-02-27 13:21
@ajoskowski , I´m still getting some errors.
[git-reset-output.txt](https://github.com/IntelAI/nauta/files/2910436/git-reset-output.txt)
[make-k8s-installer-build.log.txt](https://github.com/IntelAI/nauta/files/2910438/make-k8s-installer-build.log.txt)

**Comment by ajoskowski** [comment] 2019-02-27 13:23
You encountered `No space left on device` once again.

**Comment by fjmatos** [comment] 2019-02-27 15:00
I got a 50 GB disk partition for /nauta, so the process must create temporary files in / , where I have 2.5 GB free.
I´ll try somehow increase free space in /

**Comment by fjmatos** [comment] 2019-02-27 18:59
After almost 4 hours of compilation, I get a new error.
I see in the log file:  "fatal error: openssl/opensslv.h: No such file or directory" 
This seems to be related with  libssl-dev package, but I cannot find anything about it in the **How_to_Build_Nauta** guide.
These are ssl packages that I got installed in my Ubuntu:
libssl1.0.0
libgnutls-openssl27
openssl

I have installed libssl-dev  and launched the compilation again.

[make-k8s-installer-build.log.txt](https://github.com/IntelAI/nauta/files/2911860/make-k8s-installer-build.log.txt)

**Comment by fjmatos** [comment] 2019-02-27 21:03
Still getting errors

[make-k8s-installer-build.log.txt](https://github.com/IntelAI/nauta/files/2912305/make-k8s-installer-build.log.txt)

**Comment by mzylowski** [comment] 2019-02-28 08:19
Hello!
Now you run into problem related with CPU flags.
It's from your logs:

`The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine. `

Can you share your `cat /proc/cpuinfo` output?
I assume you build nauta on some kind of VM where your CPU not supports required flags. You need CPU with AVX and SSE flags enabled. If you build on VM maybe your virtualization mechanism allows to set missing CPU flags?

**Comment by fjmatos** [comment] 2019-03-01 08:58
Hello @mzylowski 
Thank you for your information. In the requirements, I just checked that my VM CPU was compatible with sse sse2 instructions.
I´m looking into the bios of my host (dell R510) and it looks not be able to support AVX , so I´ll try to compile nauta in a VM placed in a host with this type of flags.

**Comment by fjmatos** [comment] 2019-03-11 15:34
Hello @mzylowski 
I have installed a VM with the right flags.
With 100 GB HD for /var/lib/docker   , and 12 GB RAM, but I´m still getting some errors.

[k8s_installer_build.log](https://github.com/IntelAI/nauta/files/2952921/k8s_installer_build.log)
[cpuinfo.txt](https://github.com/IntelAI/nauta/files/2952923/cpuinfo.txt)

**Comment by ajoskowski** [comment] 2019-03-12 06:33
@fjmatos , it looks like q connection problem in your infrastructure, because you can see in logs that "connection reset by peer" error was encountered. In my opinion you should try to run `make k8s-installer-clean && make k8s-installer-build` once again. You can check also proxy settings if problem still occurs.

**Comment by fjmatos** [comment] 2019-03-12 10:10
I have run again, but now I get another kind of errors.

[k8s_installer_build.log](https://github.com/IntelAI/nauta/files/2956229/k8s_installer_build.log)

**Comment by ajoskowski** [comment] 2019-03-12 10:25
@fjmatos are you behind a corporate proxy server? If yes, did you set a proxy settings? The simplest way to set proxy settings is exporting http_proxy, HTTP_PROXY, https_proxy, HTTPS_PROXY, no_proxy and NO_PROXY environment variables with valid addresses.

**Comment by AdamTumi** [comment] 2019-03-28 10:38
I'm closing that issue, as it was resolved off-line

**Closed as completed by AdamTumi** 2019-03-28 10:38 UTC

**Comment by asispatra** [comment] 2019-05-07 09:29
@AdamTumi What was the solution?
